{% set name = "itpminer" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 733f91df16137cbe940faafa07e00b69adf4e5c7f0b01d95271a60b348022900

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - networkx
    - pandas
    - python >=3.8

test:
  imports:
    - itpminer
    - itpminer.utils
    - itpminer.utils.components

about:
  home: https://github.com/Local-E-Rewards-ML/itpminer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python implementation of ITPMiner algorithm
  doc_url: https://github.com/Local-E-Rewards-ML/itpminer
  dev_url: https://github.com/Local-E-Rewards-ML/itpminer

extra:
  recipe-maintainers:
    - chanyoungs
